name: shelf_html_example
version: 0.1.0
author: George Moschovitis
description: A sample web application using shelf_html, shelf_route and Polymer.
dependencies:
  logging: any
  polymer: '>=0.10.0-pre.7'
  shelf: any
  shelf_html: any
  shelf_route: any
transformers:
- polymer:
    entry_points: web/shelf_html_example.html
