name: shelf_html_example
version: 0.1.0
author: George Moschovitis
description: A sample web application using shelf_html, shelf_route and Polymer.
dependencies:
  logging: '>=0.9.1 <0.10.0'
  polymer: '>=0.10.0-pre.7 <0.11.0'
  shelf: '>=0.5.1 <0.6.0'
  shelf_html: '>=0.2.1 <0.3.0'
  shelf_route: '>=0.5.0 <0.6.0'
transformers:
- polymer:
    entry_points: web/index.html
